### PR TITLE
Update server-Enable-link-time-optimization.mypatch

### PR DESCRIPTION
**Pull request by Nanotwerp**

### CODE REVIEW

**Comment by openglfreak** [comment]
@Nanotwerp Can you give some explanations for the changes you made?

**Comment by Nanotwerp** [comment]
> @Nanotwerp Can you give some explanations for the changes you made?

The basic changes are just refactoring so that the patch can apply. The LTO flag changes were made because I thought that they would just be redundant to keep, but I'm doubting that upon further review. 

If [this page]https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) is up to date on defaults, GCC's default LTO partitioning value of `-flto-partition=balanced' compiles units in parallel (similar to Clang's ThinLTO), with the downside of having less max potential performance due to having less cross-module optimizations. `-flto-partition=one, on the other hand, operates like Clang's Full LTO.

`-fdevirtualize-at-ltrans` seems to still be a good option for aggressive optimization too, with its only downside seeming to be that it can "significantly increase the size of the streamed data", whatever that means!

**Comment by openglfreak** [comment]
You added an unnecessary context line, you don't need more than 3. And I think we should keep the compiler flags, unless we have a good reason to remove them. It doesn't take too much time to link wineserver on my system.

**Comment by Nanotwerp** [comment]
> You added an unnecessary context line, you don't need more than 3. And I think we should keep the compiler flags, unless we have a good reason to remove them. It doesn't take too much time to link wineserver on my system.

I agree! Is this new commit better?

**Comment by openglfreak** [comment]
@Nanotwerp now the commit is essentially empty

**Comment by Nanotwerp** [comment]
> @Nanotwerp now the commit is essentially empty

Well...

This is very embarrassing! I think that I was previously using another patch that conflicted with the LTO patch, and blamed the patches failing on the wrong patch! Sorry for wasting your time!

**Pull request closed without merging**
