### PR TITLE
Update  wine_wayland_driver.mypatch to 7.20

### PR DESCRIPTION
**Pull request by Xephobia**
Update for the 7.20 version of wine
Note : This is my first contribution to a project EVER. I don't know if i used the right method to generate the patchset, all i know is that it compiles without errors (I haven't tested it yet)

### CODE REVIEW

**Comment by ptr1337** [comment]
> Update for the 7.20 version of wine Note : This is my first contribution to a project EVER. I don't know if i used the right method to generate the patchset, all i know is that it compiles without errors (I haven't tested it yet)

It seems more like you removed the whole patchset, instead of updating it

**Comment by Xephobia** [comment]
> > Update for the 7.20 version of wine Note : This is my first contribution to a project EVER. I don't know if i used the right method to generate the patchset, all i know is that it compiles without errors (I haven't tested it yet)
> 
> It seems more like you removed the whole patchset, instead of updating it

I made the patch from scratch, how do i "update" it?

**Comment by ptr1337** [comment]
> > > Update for the 7.20 version of wine Note : This is my first contribution to a project EVER. I don't know if i used the right method to generate the patchset, all i know is that it compiles without errors (I haven't tested it yet)
> > 
> > 
> > It seems more like you removed the whole patchset, instead of updating it
> 
> I made the patch from scratch, how do i "update" it?

Make a diff from 7.20 tag to the latest wine wayland branch commit. (https://gitlab.collabora.com/alf/wine/-/tree/wayland)

I did update the patch, feel free to test it and update it then:
https://paste.cachyos.org/p/be77060.diff

**Comment by Xephobia** [comment]
is this okay now?

**Comment by ptr1337** [comment]
> is this okay now?

I made a diff against the one I sent you, and it seems to be completely equal :)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/community-patches/commit/d7115ba3fe7778d7d5513ac1983fc26fed2cd7ee

**Pull request closed without merging**
