### PR TITLE
Split SizeHeap patches in staging/non-staging, rebase legoisland and …

### PR DESCRIPTION
**Pull request by llde**
…no-above-state patches, add patch to fix double buffered listview black screen

### CODE REVIEW

**Comment by llde** [comment]
Also provided the LFH patchset version of GlobalLock pointers for RtlSizeHeap, removed the patches that dealt with GMEM_MOVEABLE global memory as too broken

**Comment by llde** [comment]
Close #110

**Comment by Tk-Glitch** [comment]
Many heap changes upstream lately for sure

**Comment by Tk-Glitch** [comment]
Thanks llde, I was kinda nervous about the incoming breakage but that'll make it a better base for a possible rebase down the line.

**Comment by llde** [comment]
Thanks @Ember2528  will take a look tomorrow, if there are no incoming atches that touch heap in upstream

**Pull request merged**
