### PR TITLE
Add RDTSC spoofing patch

### PR DESCRIPTION
**Pull request by aspenluxxxy**
https://github.com/WCharacter/RDTSC-KVM-Handler

Applies cleanly against both 5.9 and 5.10-rc7

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
Thanks!

**Comment by aspenluxxxy** [comment]
Wait, I just realized that I had accidentally messed up the patch, and just pushed a fix:

` +	set_intercept(svm, INTERCEPT_RDTSC);`
needs to be
` +	svm_set_intercept(svm, INTERCEPT_RDTSC);`

**Comment by Tk-Glitch** [comment]
Thanks, I'll update the patch

**Comment by aspenluxxxy** [comment]
I just pushed the fix here if you just wanna cherry-pick the commit: https://github.com/aspenluxxxy/community-patches/commit/f617763e1b5e0bec33127d217caace4826b492b6

**Pull request merged**
